[[main]]
none = "none"

[[main]]
name = "technosignatures"
url = "https://open-research.gemmadanks.com/"

[[main]]
name = "palebluemarbles"
url = "https://palebluemarbles.com"

[[footer]]
none = "none"
